development: 
  adapter: postgresql
  encoding: unicode
  database: zad_development
  pool: 5 
  username: Yousef
  password: 
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: zad_test
  pool: 5 
  username: Yousef
  password: 
  timeout: 5000